/** Short FR translations for illustrated A–Z / everyday picture sheets. */
const EVERYDAY: Record<string, string> = {
  apple: 'pomme',
  pomme: 'apple',
  ball: 'ballon',
  ballon: 'ball',
  cat: 'chat',
  chat: 'cat',
  dog: 'chien',
  chien: 'dog',
  egg: 'œuf',
  oeuf: 'egg',
  œuf: 'egg',
  fish: 'poisson',
  poisson: 'fish',
  goat: 'chèvre',
  chevre: 'goat',
  chèvre: 'goat',
  hat: 'chapeau',
  chapeau: 'hat',
  ice: 'glace',
  glace: 'ice',
  jug: 'cruche',
  cruche: 'jug',
  carafe: 'jug',
  pitcher: 'cruche',
  kite: 'cerf-volant',
  'cerf-volant': 'kite',
  lion: 'félin',
  milk: 'lait',
  lait: 'milk',
  orange: 'un fruit',
  pen: 'stylo',
  stylo: 'pen',
  pencil: 'crayon',
  crayon: 'pencil',
  queen: 'reine',
  reine: 'queen',
  bird: 'oiseau',
  oiseau: 'bird',
  book: 'livre',
  livre: 'book',
  car: 'voiture',
  voiture: 'car',
  house: 'maison',
  maison: 'house',
  tree: 'arbre',
  arbre: 'tree',
  sun: 'soleil',
  soleil: 'sun',
  moon: 'lune',
  lune: 'moon',
  flower: 'fleur',
  fleur: 'flower',
  shoe: 'chaussure',
  chaussure: 'shoe',
  door: 'porte',
  porte: 'door',
  chair: 'chaise',
  chaise: 'chair',
  table: 'meuble',
  bed: 'lit',
  lit: 'bed',
  cup: 'tasse',
  tasse: 'cup',
  plate: 'assiette',
  assiette: 'plate',
  cheese: 'fromage',
  fromage: 'cheese',
  bread: 'pain',
  pain: 'bread',
  water: 'eau',
  eau: 'water',
  banana: 'banane',
  banane: 'banana',
  pizza: 'une part',
  school: 'école',
  ecole: 'school',
  école: 'school',
  window: 'fenêtre',
  fenetre: 'window',
  fenêtre: 'window',
  train: 'locomotive',
  boat: 'bateau',
  bateau: 'boat',
  plane: 'avion',
  airplane: 'avion',
  avion: 'plane',
  bus: 'autocar',
  key: 'clé',
  cle: 'key',
  clé: 'key',
  clock: 'horloge',
  horloge: 'clock',
  phone: 'téléphone',
  telephone: 'phone',
  téléphone: 'phone',
  bag: 'sac',
  sac: 'bag',
  umbrella: 'parapluie',
  parapluie: 'umbrella',
  cloud: 'nuage',
  nuage: 'cloud',
};

function normalizeKey(word: string): string {
  return word
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .replace(/[^a-z0-9'-]/g, '');
}

export function lookupEverydayGloss(word: string): string | null {
  const key = normalizeKey(word);
  if (!key) return null;
  const gloss = EVERYDAY[key];
  if (!gloss) return null;
  if (normalizeKey(gloss) === key) return null;
  return gloss;
}
