import type { WordPair } from '../types';

const VISUAL_MAP: Record<string, string> = {
  cahier: '📓',
  notebook: '📓',
  notitieboek: '📓',
  cuaderno: '📓',
  livre: '📖',
  book: '📖',
  boek: '📖',
  libro: '📖',
  stylo: '🖊️',
  pen: '🖊️',
  plume: '🖊️',
  bolígrafo: '🖊️',
  crayon: '✏️',
  pencil: '✏️',
  potlood: '✏️',
  lápiz: '✏️',
  gomme: '🧽',
  eraser: '🧽',
  gum: '🧽',
  gom: '🧽',
  borrador: '🧽',
  règle: '📏',
  rule: '📏',
  ruler: '📏',
  liniaal: '📏',
  regla: '📏',
  sac: '🎒',
  bag: '🎒',
  tas: '🎒',
  backpack: '🎒',
  rugzak: '🎒',
  mochila: '🎒',
  table: '🪑',
  bureau: '🪑',
  desk: '🪑',
  stoel: '🪑',
  chair: '🪑',
  silla: '🪑',
  chaise: '🪑',
  maison: '🏠',
  house: '🏠',
  huis: '🏠',
  casa: '🏠',
  chien: '🐕',
  dog: '🐕',
  hond: '🐕',
  perro: '🐕',
  chat: '🐈',
  cat: '🐈',
  kat: '🐈',
  gato: '🐈',
  oiseau: '🐦',
  bird: '🐦',
  vogel: '🐦',
  pájaro: '🐦',
  poisson: '🐟',
  fish: '🐟',
  vis: '🐟',
  pez: '🐟',
  cheval: '🐴',
  horse: '🐴',
  paard: '🐴',
  caballo: '🐴',
  vache: '🐄',
  cow: '🐄',
  koe: '🐄',
  vaca: '🐄',
  mouton: '🐑',
  sheep: '🐑',
  schaap: '🐑',
  oveja: '🐑',
  pomme: '🍎',
  apple: '🍎',
  appel: '🍎',
  manzana: '🍎',
  banane: '🍌',
  banana: '🍌',
  banaan: '🍌',
  plátano: '🍌',
  orange: '🍊',
  sinaasappel: '🍊',
  naranja: '🍊',
  pain: '🍞',
  bread: '🍞',
  brood: '🍞',
  pan: '🍞',
  lait: '🥛',
  milk: '🥛',
  melk: '🥛',
  leche: '🥛',
  eau: '💧',
  water: '💧',
  agua: '💧',
  café: '☕',
  coffee: '☕',
  koffie: '☕',
  soleil: '☀️',
  sun: '☀️',
  zon: '☀️',
  sol: '☀️',
  lune: '🌙',
  moon: '🌙',
  maan: '🌙',
  luna: '🌙',
  voiture: '🚗',
  car: '🚗',
  auto: '🚗',
  coche: '🚗',
  vélo: '🚲',
  bike: '🚲',
  bicycle: '🚲',
  fiets: '🚲',
  bicicleta: '🚲',
  train: '🚆',
  trein: '🚆',
  tren: '🚆',
  avion: '✈️',
  plane: '✈️',
  airplane: '✈️',
  vliegtuig: '✈️',
  avión: '✈️',
  arbre: '🌳',
  tree: '🌳',
  boom: '🌳',
  árbol: '🌳',
  fleur: '🌸',
  flower: '🌸',
  bloem: '🌸',
  flor: '🌸',
  montagne: '⛰️',
  mountain: '⛰️',
  berg: '⛰️',
  montaña: '⛰️',
  mer: '🌊',
  sea: '🌊',
  zee: '🌊',
  mar: '🌊',
  école: '🏫',
  school: '🏫',
  escuela: '🏫',
  professeur: '👩‍🏫',
  teacher: '👩‍🏫',
  leraar: '👩‍🏫',
  profe: '👩‍🏫',
  élève: '🧑‍🎓',
  student: '🧑‍🎓',
  leerling: '🧑‍🎓',
  estudiante: '🧑‍🎓',
  horloge: '🕐',
  clock: '🕐',
  klok: '🕐',
  reloj: '🕐',
  téléphone: '📱',
  phone: '📱',
  telefoon: '📱',
  teléfono: '📱',
  ordinateur: '💻',
  computer: '💻',
  laptop: '💻',
  ordenador: '💻',
  porte: '🚪',
  door: '🚪',
  deur: '🚪',
  puerta: '🚪',
  fenêtre: '🪟',
  window: '🪟',
  raam: '🪟',
  ventana: '🪟',
  lit: '🛏️',
  bed: '🛏️',
  cama: '🛏️',
  ballon: '⚽',
  ball: '⚽',
  bal: '⚽',
  pelota: '⚽',
  football: '⚽',
  foot: '⚽',
  voetbal: '⚽',
  fútbol: '⚽',
};

function normalizeWord(raw: string): string {
  return raw
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .replace(/^(de|het|een|le|la|les|un|une|the|a|an|el|la|los|las)\s+/i, '')
    .replace(/[^a-z0-9\s'-]/g, '')
    .trim();
}

function lookupVisual(text: string): string | null {
  const word = normalizeWord(text);
  if (!word) return null;
  if (VISUAL_MAP[word]) return VISUAL_MAP[word];
  const first = word.split(/\s+/)[0];
  return VISUAL_MAP[first] ?? null;
}

export function resolvePairVisual(pair: WordPair): string | null {
  return lookupVisual(pair.term) ?? lookupVisual(pair.definition);
}

export function enrichPairsWithVisuals(pairs: WordPair[]): WordPair[] {
  return pairs.map((pair) => {
    const visual = resolvePairVisual(pair);
    if (!visual) return pair;
    return { ...pair, visual };
  });
}
