-- ============================================================
-- OBSOLÈTE — Utiliser plutôt :
--   supabase/migration-scan-coins-system.sql
-- (version complète : portefeuille, historique, sync, transferts)
-- ============================================================
